project:
  type: book
  output-dir: docs

book:
  title: "Methods for quantifying the impact of welfare threats on shrimp"
  author: "Hannah McKay and William McAuliffe"
  repo-url: https://github.com/rethinkpriorities/quantifying_shrimp_pain/
  repo-actions: [issue]
  date: today
  chapters:
    - index.qmd
    - chapters/set-up.qmd
    - part: "Welfare threats"
      chapters: 
        - chapters/water_quality.qmd
        - chapters/pond_habitat.qmd
        - chapters/feed_management.qmd
        - chapters/health.qmd
        - chapters/transportation.qmd
        - chapters/harvest_slaughter.qmd
    - chapters/results.qmd
  reader-mode: true

format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: flatly
    code-overflow: wrap
    code-copy: true
    toc: true
    toc-expand: 2
    callout-appearance: simple
    number-depth: 3
    callout-icon: false
    number-sections: false

editor: source

